[package]
name = "quito-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "quito"
path = "src/main.rs"

[dependencies]
quito-syntax = { workspace = true }
quito-eval = { workspace = true }
quito-geom = { workspace = true }
quito-ir = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
png = { workspace = true }
